project:
  type: manuscript

execute:
  freeze: auto

format:
  elsevier-pdf:
    keep-tex: true
  elsevier-html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default

bibliography: bibliography.bib
